// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9KHqhbTqGuL1fym5lCxjWUqW8iRYboz8',
    appId: '1:998646811182:web:046b687290ef746eff6dbf',
    messagingSenderId: '998646811182',
    projectId: 'anigest-6499b',
    authDomain: 'anigest-6499b.firebaseapp.com',
    storageBucket: 'anigest-6499b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxgDeN66nXKvLanDWEoMSJV7lkInkEAA',
    appId: '1:998646811182:android:3c0beec35886bcb2ff6dbf',
    messagingSenderId: '998646811182',
    projectId: 'anigest-6499b',
    storageBucket: 'anigest-6499b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTB208P5XtTQNxlZvJ3cuBd0MMfcIEK30',
    appId: '1:998646811182:ios:fb35f40bc035a6beff6dbf',
    messagingSenderId: '998646811182',
    projectId: 'anigest-6499b',
    storageBucket: 'anigest-6499b.appspot.com',
    iosClientId: '998646811182-278gq214tlqed5i148umjtkfd627vm91.apps.googleusercontent.com',
    iosBundleId: 'com.example.anigest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTB208P5XtTQNxlZvJ3cuBd0MMfcIEK30',
    appId: '1:998646811182:ios:fb35f40bc035a6beff6dbf',
    messagingSenderId: '998646811182',
    projectId: 'anigest-6499b',
    storageBucket: 'anigest-6499b.appspot.com',
    iosClientId: '998646811182-278gq214tlqed5i148umjtkfd627vm91.apps.googleusercontent.com',
    iosBundleId: 'com.example.anigest',
  );
}
